controllers_front:
    resource: ../src/Controller/Front
    type: attribute
    name_prefix: front_

controllers_manager:
    resource: ../src/Controller/Manager
    type: attribute
    name_prefix: manager_
    prefix: /manager/

controllers_back:
    resource: ../src/Controller/Back
    type: attribute
    name_prefix: back_
    prefix: /admin/

controller_security:
    resource: ../src/Controller/SecurityController.php
    type: attribute
